version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: /workspaces/phoneBookBe/Dockerfile 
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootRoot@123
      MYSQL_DATABASE: phonebook
      MYSQL_USER: rootRoot@123
      MYSQL_PASSWORD: Root@123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: